import type { ArticlePath } from '../generated/manifest';
import { localizedPath, type Locale } from './i18n';

const groups = [
  {
    id: 'reference',
    title: { zh: '参考入口', en: 'Reference entry points' },
    entries: [
      { path: '/reference/', keywords: ['overview', '总览'] },
      {
        path: '/reference/builtins/',
        keywords: [
          'builtin',
          'API',
          'print',
          'println',
          'eprint',
          'eprintln',
          'assert',
          'check',
          'require',
          'fail',
          'addressof',
          'len',
          'is_empty',
          'append',
          'append_format',
          'as_str',
          'as_slice',
          'slice',
          'push',
          'clear',
          'from_u32_unchecked',
          'from_utf8_unchecked',
          '内建',
          '函数',
        ],
      },
      {
        path: '/reference/library/',
        keywords: [
          'library',
          'std',
          'UTF8Error',
          'UTF8ErrorKind',
          'UnicodeScalarError',
          'UTF8Encoded',
          'UTF8DecodeResult',
          'UTF8Validator',
          'ByteBlock',
          'FloatBlock',
          'char_from_u32',
          'encode_utf8',
          'decode_utf8_prefix',
          'validate_utf8',
          'from_utf8',
          'to_string',
          'block_count',
          'load_block',
          'count_byte',
          'first_or',
          'find_byte',
          'ascii_digit',
          'ascii_whitespace',
          'ascii_lower',
          'ascii_prefix',
          'extract',
          'shift_in',
          'shift_left',
          'shift_right',
          'swizzle',
          'store',
          'store_partial',
          'crafts',
          'API',
          'standard',
          'utf',
          'simd',
          '标准库',
          '模块',
        ],
      },
    ],
  },
  {
    id: 'syntax',
    title: { zh: '基础语法', en: 'Syntax' },
    entries: [
      {
        path: '/reference/keywords/',
        keywords: [
          'keyword',
          '关键字',
          'self',
          'reserved',
          'contextual',
          '上下文',
          'cpp',
          'prefix',
          '保留',
        ],
      },
      {
        path: '/reference/lexical/',
        keywords: [
          'identifier',
          'comment',
          'literal',
          '注释',
          '标识符',
          'true',
          'false',
          'nullptr',
          'r"',
          'c"',
        ],
      },
    ],
  },
  {
    id: 'values',
    title: { zh: '类型与变量', en: 'Types and variables' },
    entries: [
      {
        path: '/reference/types/',
        keywords: ['bool', 'char', 'i32', 'usize', 'f64', 'void', 'as', '转换', 'inference'],
      },
      {
        path: '/reference/bindings/',
        keywords: ['let', 'var', 'const', '_', 'scope', '赋值', '作用域', '初始化'],
      },
      {
        path: '/reference/operators/',
        keywords: [
          'operator',
          'expression',
          '运算符',
          '表达式',
          '+',
          '-',
          '*',
          '/',
          '%',
          '!',
          '~',
          '==',
          '!=',
          '<',
          '>',
          '<=',
          '>=',
          '&',
          '|',
          '^',
          '&&',
          '||',
          '<<',
          '>>',
          '=',
          '+=',
          '++',
          '--',
          '..',
          '..=',
          'as',
        ],
      },
    ],
  },
  {
    id: 'control',
    title: { zh: '控制流', en: 'Control flow' },
    entries: [
      {
        path: '/reference/control/',
        keywords: [
          'if',
          'else',
          'while',
          'for',
          'in',
          'match',
          'is',
          'break',
          'continue',
          'return',
          'loop',
          'pattern',
          '循环',
          '模式',
        ],
      },
      {
        path: '/reference/failures/',
        keywords: ['throw', 'try', 'catch', 'rethrow', '?', 'failure', '失败', '恢复'],
      },
    ],
  },
  {
    id: 'declarations',
    title: { zh: '函数与数据类型', en: 'Functions and data types' },
    entries: [
      {
        path: '/reference/functions/',
        keywords: ['fn', '=>', 'parameter', 'return', 'self', '函数', '参数'],
      },
      { path: '/reference/closures/', keywords: ['lambda', 'capture', 'callable', '闭包', '捕获'] },
      {
        path: '/reference/aggregates/',
        keywords: ['struct', 'class', 'enum', 'self', 'array', '数组', '构造', '字段'],
      },
      { path: '/reference/slices/', keywords: ['slice', '[T]', '切片'] },
      {
        path: '/reference/ownership/',
        keywords: [
          'read',
          'write',
          'take',
          '&',
          '&&',
          'borrow',
          'lifetime',
          '所有权',
          '借用',
          '生命周期',
        ],
      },
      {
        path: '/reference/pointers/',
        keywords: ['ptr', 'nullptr', 'addressof', '->', '指针', '地址'],
      },
    ],
  },
  {
    id: 'text',
    title: { zh: '文本与输出', en: 'Text and output' },
    entries: [
      {
        path: '/reference/text/',
        keywords: ['str', 'String', 'char', 'raw', 'multiline', '字符串', '原始', '多行'],
      },
      {
        path: '/reference/formatting/',
        keywords: [
          'f"',
          'print',
          'println',
          'eprint',
          'eprintln',
          'format',
          '插值',
          '格式化',
          '打印',
        ],
      },
    ],
  },
  {
    id: 'program',
    title: { zh: '模块、编译期与测试', en: 'Modules and execution' },
    entries: [
      {
        path: '/reference/modules/',
        keywords: ['import', 'using', 'export', 'private', 'module', 'craft', '模块', '可见性'],
      },
      {
        path: '/reference/constants/',
        keywords: [
          'const',
          'const fn',
          'const if',
          'const for',
          'static',
          '常量',
          '编译期',
          '静态',
        ],
      },
      {
        path: '/reference/entry-testing/',
        keywords: [
          'main',
          'test',
          'const test',
          'assert',
          'check',
          'require',
          'fail',
          '入口',
          '测试',
          '断言',
        ],
      },
      {
        path: '/reference/interop/',
        keywords: ['import(cpp)', 'export(cpp)', '#[cpp]', 'C++', 'native', '互操作'],
      },
    ],
  },
  {
    id: 'library',
    title: { zh: '标准库', en: 'Standard library' },
    entries: [
      { path: '/reference/utf/', keywords: ['utf', 'unicode', 'encoding', '编码'] },
      {
        path: '/reference/simd/',
        keywords: ['simd', 'vector', 'mask', 'u8x16', 'f32x4', '向量', '掩码'],
      },
    ],
  },
  {
    id: 'tools',
    title: { zh: '工具链与附录', en: 'Tools and appendices' },
    entries: [
      {
        path: '/reference/cli/',
        keywords: ['cli', 'graver', 'check', 'compile', 'interpret', 'format', '命令'],
      },
      { path: '/reference/toolchain/', keywords: ['build', 'xmake', 'toolchain', '构建'] },
      {
        path: '/reference/grammar/',
        keywords: ['ebnf', 'grammar', 'precedence', '语法', '优先级'],
      },
      {
        path: '/reference/diagnostics/',
        keywords: ['diagnostic', 'error', 'warning', 'CV-', '诊断', '错误'],
      },
    ],
  },
] as const;

export function referenceNavigationGroups(locale: Locale) {
  return groups.map((group) => ({
    id: group.id,
    title: group.title[locale],
    entries: group.entries.map((entry) => ({
      path: localizedPath(entry.path, locale) as ArticlePath,
      keywords: entry.keywords as readonly string[],
    })),
  }));
}
