"""Create local, unicode-range-split Resource Han Rounded webfonts.

Run with Python, fonttools[woff], and Brotli installed:
  python scripts/subset-chinese-font.py /path/to/extracted/RHR-CN-0.990
This is an asset maintenance command, not a build dependency.
"""

import argparse
import shutil
import tempfile
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent


def unicode_ranges(points):
    ranges = []
    start = end = points[0]
    for point in points[1:]:
        if point == end + 1:
            end = point
        else:
            ranges.append((start, end))
            start = end = point
    ranges.append((start, end))
    return ", ".join(
        f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}"
        for start, end in ranges
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    args = parser.parse_args()
    destination = ROOT / "public/fonts/resource-han-rounded"
    destination.parent.mkdir(parents=True, exist_ok=True)
    authored = set()
    for path in sorted((ROOT / "src").rglob("*")):
        if path.suffix in {".md", ".ts", ".tsx"} and "generated" not in path.parts:
            authored.update(map(ord, path.read_text(encoding="utf-8")))
    staging = Path(
        tempfile.mkdtemp(prefix=".resource-han-rounded-", dir=destination.parent)
    )
    fonts = staging / "next"
    backup = staging / "previous"
    installed = committed = False
    try:
        fonts.mkdir()
        generate(args.source, authored, fonts, staging / "chinese-rounded.css")
        if destination.exists():
            destination.rename(backup)
        fonts.rename(destination)
        installed = True
        (staging / "chinese-rounded.css").replace(ROOT / "src/styles/chinese-rounded.css")
        committed = True
    except BaseException:
        try:
            if installed:
                shutil.rmtree(destination)
            if backup.exists():
                backup.rename(destination)
        except Exception as error:
            raise RuntimeError(
                f"Font rollback failed; original fonts retained at {backup}"
            ) from error
        raise
    finally:
        # Retain the original fonts if an unexpected filesystem error prevents rollback.
        if committed or not backup.exists():
            shutil.rmtree(staging)


def generate(source_directory, authored, destination, stylesheet):
    css = ["/* Generated by scripts/subset-chinese-font.py. Do not edit by hand. */"]
    for style, weight in [("Regular", 400), ("Medium", 500)]:
        source = source_directory / f"ResourceHanRoundedCN-{style}.ttf"
        with TTFont(source) as font:
            # Leave Latin and Latin punctuation to Nunito. Keep CJK punctuation,
            # kana, Han, and full-width forms in their original CN glyph forms.
            supported = {point for point in font.getBestCmap() if point >= 0x2E80}
        common = sorted(supported & authored)
        remaining = sorted(supported - authored)
        groups = [("common", common)] + [
            (f"extra-{offset // 512:02}", remaining[offset : offset + 512])
            for offset in range(0, len(remaining), 512)
        ]
        for name, points in groups:
            if not points:
                continue
            filename = f"{style.lower()}-{name}.woff2"
            options = subset.Options()
            options.flavor = "woff2"
            options.recalc_timestamp = False
            with TTFont(source, recalcTimestamp=False) as font:
                cutter = subset.Subsetter(options=options)
                cutter.populate(unicodes=points)
                cutter.subset(font)
                font.flavor = "woff2"
                font.save(destination / filename)
            css.append(
                "@font-face {\n"
                "  font-family: 'Carven Chinese';\n"
                f"  src: url('/fonts/resource-han-rounded/{filename}') format('woff2');\n"
                "  font-style: normal;\n"
                f"  font-weight: {weight};\n"
                "  font-display: swap;\n"
                f"  unicode-range: {unicode_ranges(points)};\n"
                "}"
            )
        print(f"{style}: {len(common)} common glyphs; {len(groups) - 1} fallback shards")
    stylesheet.write_text("\n".join(css) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
