/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as FeaturesCompileTimeRouteImport } from './routes/features.compile-time'
import { Route as FeaturesCppGenerationRouteImport } from './routes/features.cpp-generation'
import { Route as FeaturesFailureContractsRouteImport } from './routes/features.failure-contracts'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnAggregatesRouteImport } from './routes/learn.aggregates'
import { Route as LearnClosuresRouteImport } from './routes/learn.closures'
import { Route as LearnConstantsRouteImport } from './routes/learn.constants'
import { Route as LearnControlRouteImport } from './routes/learn.control'
import { Route as LearnFailuresRouteImport } from './routes/learn.failures'
import { Route as LearnFormattingRouteImport } from './routes/learn.formatting'
import { Route as LearnFunctionsRouteImport } from './routes/learn.functions'
import { Route as LearnInteropRouteImport } from './routes/learn.interop'
import { Route as LearnModulesRouteImport } from './routes/learn.modules'
import { Route as LearnOwnershipRouteImport } from './routes/learn.ownership'
import { Route as LearnPointersRouteImport } from './routes/learn.pointers'
import { Route as LearnProjectRouteImport } from './routes/learn.project'
import { Route as LearnTestingRouteImport } from './routes/learn.testing'
import { Route as LearnTextRouteImport } from './routes/learn.text'
import { Route as LearnValuesRouteImport } from './routes/learn.values'
import { Route as LearnWorkflowRouteImport } from './routes/learn.workflow'
import { Route as ReferenceIndexRouteImport } from './routes/reference.index'
import { Route as ReferenceAggregatesRouteImport } from './routes/reference.aggregates'
import { Route as ReferenceCliRouteImport } from './routes/reference.cli'
import { Route as ReferenceClosuresRouteImport } from './routes/reference.closures'
import { Route as ReferenceConstantsRouteImport } from './routes/reference.constants'
import { Route as ReferenceControlRouteImport } from './routes/reference.control'
import { Route as ReferenceDiagnosticsRouteImport } from './routes/reference.diagnostics'
import { Route as ReferenceEntryTestingRouteImport } from './routes/reference.entry-testing'
import { Route as ReferenceFailuresRouteImport } from './routes/reference.failures'
import { Route as ReferenceFormattingRouteImport } from './routes/reference.formatting'
import { Route as ReferenceFunctionsRouteImport } from './routes/reference.functions'
import { Route as ReferenceGrammarRouteImport } from './routes/reference.grammar'
import { Route as ReferenceInteropRouteImport } from './routes/reference.interop'
import { Route as ReferenceLexicalRouteImport } from './routes/reference.lexical'
import { Route as ReferenceModulesRouteImport } from './routes/reference.modules'
import { Route as ReferenceOwnershipRouteImport } from './routes/reference.ownership'
import { Route as ReferencePointersRouteImport } from './routes/reference.pointers'
import { Route as ReferenceSlicesRouteImport } from './routes/reference.slices'
import { Route as ReferenceTextRouteImport } from './routes/reference.text'
import { Route as ReferenceToolchainRouteImport } from './routes/reference.toolchain'
import { Route as ReferenceTypesRouteImport } from './routes/reference.types'
import { Route as ReferenceUtfRouteImport } from './routes/reference.utf'
import { Route as ZhIndexRouteImport } from './routes/zh.index'
import { Route as Zh404RouteImport } from './routes/zh.404'
import { Route as ZhPhilosophyRouteImport } from './routes/zh.philosophy'
import { Route as ZhUseCasesRouteImport } from './routes/zh.use-cases'
import { Route as ZhFeaturesCompileTimeRouteImport } from './routes/zh.features.compile-time'
import { Route as ZhFeaturesCppGenerationRouteImport } from './routes/zh.features.cpp-generation'
import { Route as ZhFeaturesFailureContractsRouteImport } from './routes/zh.features.failure-contracts'
import { Route as ZhLearnIndexRouteImport } from './routes/zh.learn.index'
import { Route as ZhLearnAggregatesRouteImport } from './routes/zh.learn.aggregates'
import { Route as ZhLearnClosuresRouteImport } from './routes/zh.learn.closures'
import { Route as ZhLearnConstantsRouteImport } from './routes/zh.learn.constants'
import { Route as ZhLearnControlRouteImport } from './routes/zh.learn.control'
import { Route as ZhLearnFailuresRouteImport } from './routes/zh.learn.failures'
import { Route as ZhLearnFormattingRouteImport } from './routes/zh.learn.formatting'
import { Route as ZhLearnFunctionsRouteImport } from './routes/zh.learn.functions'
import { Route as ZhLearnInteropRouteImport } from './routes/zh.learn.interop'
import { Route as ZhLearnModulesRouteImport } from './routes/zh.learn.modules'
import { Route as ZhLearnOwnershipRouteImport } from './routes/zh.learn.ownership'
import { Route as ZhLearnPointersRouteImport } from './routes/zh.learn.pointers'
import { Route as ZhLearnProjectRouteImport } from './routes/zh.learn.project'
import { Route as ZhLearnTestingRouteImport } from './routes/zh.learn.testing'
import { Route as ZhLearnTextRouteImport } from './routes/zh.learn.text'
import { Route as ZhLearnValuesRouteImport } from './routes/zh.learn.values'
import { Route as ZhLearnWorkflowRouteImport } from './routes/zh.learn.workflow'
import { Route as ZhReferenceIndexRouteImport } from './routes/zh.reference.index'
import { Route as ZhReferenceAggregatesRouteImport } from './routes/zh.reference.aggregates'
import { Route as ZhReferenceCliRouteImport } from './routes/zh.reference.cli'
import { Route as ZhReferenceClosuresRouteImport } from './routes/zh.reference.closures'
import { Route as ZhReferenceConstantsRouteImport } from './routes/zh.reference.constants'
import { Route as ZhReferenceControlRouteImport } from './routes/zh.reference.control'
import { Route as ZhReferenceDiagnosticsRouteImport } from './routes/zh.reference.diagnostics'
import { Route as ZhReferenceEntryTestingRouteImport } from './routes/zh.reference.entry-testing'
import { Route as ZhReferenceFailuresRouteImport } from './routes/zh.reference.failures'
import { Route as ZhReferenceFormattingRouteImport } from './routes/zh.reference.formatting'
import { Route as ZhReferenceFunctionsRouteImport } from './routes/zh.reference.functions'
import { Route as ZhReferenceGrammarRouteImport } from './routes/zh.reference.grammar'
import { Route as ZhReferenceInteropRouteImport } from './routes/zh.reference.interop'
import { Route as ZhReferenceLexicalRouteImport } from './routes/zh.reference.lexical'
import { Route as ZhReferenceModulesRouteImport } from './routes/zh.reference.modules'
import { Route as ZhReferenceOwnershipRouteImport } from './routes/zh.reference.ownership'
import { Route as ZhReferencePointersRouteImport } from './routes/zh.reference.pointers'
import { Route as ZhReferenceSlicesRouteImport } from './routes/zh.reference.slices'
import { Route as ZhReferenceTextRouteImport } from './routes/zh.reference.text'
import { Route as ZhReferenceToolchainRouteImport } from './routes/zh.reference.toolchain'
import { Route as ZhReferenceTypesRouteImport } from './routes/zh.reference.types'
import { Route as ZhReferenceUtfRouteImport } from './routes/zh.reference.utf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesCompileTimeRoute = FeaturesCompileTimeRouteImport.update({
  id: '/features/compile-time',
  path: '/features/compile-time',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesCppGenerationRoute = FeaturesCppGenerationRouteImport.update({
  id: '/features/cpp-generation',
  path: '/features/cpp-generation',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesFailureContractsRoute =
  FeaturesFailureContractsRouteImport.update({
    id: '/features/failure-contracts',
    path: '/features/failure-contracts',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnAggregatesRoute = LearnAggregatesRouteImport.update({
  id: '/learn/aggregates',
  path: '/learn/aggregates',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnClosuresRoute = LearnClosuresRouteImport.update({
  id: '/learn/closures',
  path: '/learn/closures',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnConstantsRoute = LearnConstantsRouteImport.update({
  id: '/learn/constants',
  path: '/learn/constants',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnControlRoute = LearnControlRouteImport.update({
  id: '/learn/control',
  path: '/learn/control',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnFailuresRoute = LearnFailuresRouteImport.update({
  id: '/learn/failures',
  path: '/learn/failures',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnFormattingRoute = LearnFormattingRouteImport.update({
  id: '/learn/formatting',
  path: '/learn/formatting',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnFunctionsRoute = LearnFunctionsRouteImport.update({
  id: '/learn/functions',
  path: '/learn/functions',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnInteropRoute = LearnInteropRouteImport.update({
  id: '/learn/interop',
  path: '/learn/interop',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnModulesRoute = LearnModulesRouteImport.update({
  id: '/learn/modules',
  path: '/learn/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnOwnershipRoute = LearnOwnershipRouteImport.update({
  id: '/learn/ownership',
  path: '/learn/ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPointersRoute = LearnPointersRouteImport.update({
  id: '/learn/pointers',
  path: '/learn/pointers',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnProjectRoute = LearnProjectRouteImport.update({
  id: '/learn/project',
  path: '/learn/project',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTestingRoute = LearnTestingRouteImport.update({
  id: '/learn/testing',
  path: '/learn/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTextRoute = LearnTextRouteImport.update({
  id: '/learn/text',
  path: '/learn/text',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnValuesRoute = LearnValuesRouteImport.update({
  id: '/learn/values',
  path: '/learn/values',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnWorkflowRoute = LearnWorkflowRouteImport.update({
  id: '/learn/workflow',
  path: '/learn/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceIndexRoute = ReferenceIndexRouteImport.update({
  id: '/reference/',
  path: '/reference/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceAggregatesRoute = ReferenceAggregatesRouteImport.update({
  id: '/reference/aggregates',
  path: '/reference/aggregates',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceCliRoute = ReferenceCliRouteImport.update({
  id: '/reference/cli',
  path: '/reference/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceClosuresRoute = ReferenceClosuresRouteImport.update({
  id: '/reference/closures',
  path: '/reference/closures',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceConstantsRoute = ReferenceConstantsRouteImport.update({
  id: '/reference/constants',
  path: '/reference/constants',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceControlRoute = ReferenceControlRouteImport.update({
  id: '/reference/control',
  path: '/reference/control',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceDiagnosticsRoute = ReferenceDiagnosticsRouteImport.update({
  id: '/reference/diagnostics',
  path: '/reference/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceEntryTestingRoute = ReferenceEntryTestingRouteImport.update({
  id: '/reference/entry-testing',
  path: '/reference/entry-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceFailuresRoute = ReferenceFailuresRouteImport.update({
  id: '/reference/failures',
  path: '/reference/failures',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceFormattingRoute = ReferenceFormattingRouteImport.update({
  id: '/reference/formatting',
  path: '/reference/formatting',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceFunctionsRoute = ReferenceFunctionsRouteImport.update({
  id: '/reference/functions',
  path: '/reference/functions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceGrammarRoute = ReferenceGrammarRouteImport.update({
  id: '/reference/grammar',
  path: '/reference/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceInteropRoute = ReferenceInteropRouteImport.update({
  id: '/reference/interop',
  path: '/reference/interop',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceLexicalRoute = ReferenceLexicalRouteImport.update({
  id: '/reference/lexical',
  path: '/reference/lexical',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceModulesRoute = ReferenceModulesRouteImport.update({
  id: '/reference/modules',
  path: '/reference/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceOwnershipRoute = ReferenceOwnershipRouteImport.update({
  id: '/reference/ownership',
  path: '/reference/ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencePointersRoute = ReferencePointersRouteImport.update({
  id: '/reference/pointers',
  path: '/reference/pointers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceSlicesRoute = ReferenceSlicesRouteImport.update({
  id: '/reference/slices',
  path: '/reference/slices',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceTextRoute = ReferenceTextRouteImport.update({
  id: '/reference/text',
  path: '/reference/text',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceToolchainRoute = ReferenceToolchainRouteImport.update({
  id: '/reference/toolchain',
  path: '/reference/toolchain',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceTypesRoute = ReferenceTypesRouteImport.update({
  id: '/reference/types',
  path: '/reference/types',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceUtfRoute = ReferenceUtfRouteImport.update({
  id: '/reference/utf',
  path: '/reference/utf',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhIndexRoute = ZhIndexRouteImport.update({
  id: '/zh/',
  path: '/zh/',
  getParentRoute: () => rootRouteImport,
} as any)
const Zh404Route = Zh404RouteImport.update({
  id: '/zh/404',
  path: '/zh/404',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhPhilosophyRoute = ZhPhilosophyRouteImport.update({
  id: '/zh/philosophy',
  path: '/zh/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhUseCasesRoute = ZhUseCasesRouteImport.update({
  id: '/zh/use-cases',
  path: '/zh/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhFeaturesCompileTimeRoute = ZhFeaturesCompileTimeRouteImport.update({
  id: '/zh/features/compile-time',
  path: '/zh/features/compile-time',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhFeaturesCppGenerationRoute = ZhFeaturesCppGenerationRouteImport.update({
  id: '/zh/features/cpp-generation',
  path: '/zh/features/cpp-generation',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhFeaturesFailureContractsRoute =
  ZhFeaturesFailureContractsRouteImport.update({
    id: '/zh/features/failure-contracts',
    path: '/zh/features/failure-contracts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ZhLearnIndexRoute = ZhLearnIndexRouteImport.update({
  id: '/zh/learn/',
  path: '/zh/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLearnAggregatesRoute = ZhLearnAggregatesRouteImport.update({
  id: '/zh/learn/aggregates',
  path: '/zh/learn/aggregates',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLearnClosuresRoute = ZhLearnClosuresRouteImport.update({
  id: '/zh/learn/closures',
  path: '/zh/learn/closures',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLearnConstantsRoute = ZhLearnConstantsRouteImport.update({
  id: '/zh/learn/constants',
  path: '/zh/learn/constants',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLearnControlRoute = ZhLearnControlRouteImport.update({
  id: '/zh/learn/control',
  path: '/zh/learn/control',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLearnFailuresRoute = ZhLearnFailuresRouteImport.update({
  id: '/zh/learn/failures',
  path: '/zh/learn/failures',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLearnFormattingRoute = ZhLearnFormattingRouteImport.update({
  id: '/zh/learn/formatting',
  path: '/zh/learn/formatting',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLearnFunctionsRoute = ZhLearnFunctionsRouteImport.update({
  id: '/zh/learn/functions',
  path: '/zh/learn/functions',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLearnInteropRoute = ZhLearnInteropRouteImport.update({
  id: '/zh/learn/interop',
  path: '/zh/learn/interop',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLearnModulesRoute = ZhLearnModulesRouteImport.update({
  id: '/zh/learn/modules',
  path: '/zh/learn/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLearnOwnershipRoute = ZhLearnOwnershipRouteImport.update({
  id: '/zh/learn/ownership',
  path: '/zh/learn/ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLearnPointersRoute = ZhLearnPointersRouteImport.update({
  id: '/zh/learn/pointers',
  path: '/zh/learn/pointers',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLearnProjectRoute = ZhLearnProjectRouteImport.update({
  id: '/zh/learn/project',
  path: '/zh/learn/project',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLearnTestingRoute = ZhLearnTestingRouteImport.update({
  id: '/zh/learn/testing',
  path: '/zh/learn/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLearnTextRoute = ZhLearnTextRouteImport.update({
  id: '/zh/learn/text',
  path: '/zh/learn/text',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLearnValuesRoute = ZhLearnValuesRouteImport.update({
  id: '/zh/learn/values',
  path: '/zh/learn/values',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhLearnWorkflowRoute = ZhLearnWorkflowRouteImport.update({
  id: '/zh/learn/workflow',
  path: '/zh/learn/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceIndexRoute = ZhReferenceIndexRouteImport.update({
  id: '/zh/reference/',
  path: '/zh/reference/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceAggregatesRoute = ZhReferenceAggregatesRouteImport.update({
  id: '/zh/reference/aggregates',
  path: '/zh/reference/aggregates',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceCliRoute = ZhReferenceCliRouteImport.update({
  id: '/zh/reference/cli',
  path: '/zh/reference/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceClosuresRoute = ZhReferenceClosuresRouteImport.update({
  id: '/zh/reference/closures',
  path: '/zh/reference/closures',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceConstantsRoute = ZhReferenceConstantsRouteImport.update({
  id: '/zh/reference/constants',
  path: '/zh/reference/constants',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceControlRoute = ZhReferenceControlRouteImport.update({
  id: '/zh/reference/control',
  path: '/zh/reference/control',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceDiagnosticsRoute = ZhReferenceDiagnosticsRouteImport.update({
  id: '/zh/reference/diagnostics',
  path: '/zh/reference/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceEntryTestingRoute = ZhReferenceEntryTestingRouteImport.update({
  id: '/zh/reference/entry-testing',
  path: '/zh/reference/entry-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceFailuresRoute = ZhReferenceFailuresRouteImport.update({
  id: '/zh/reference/failures',
  path: '/zh/reference/failures',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceFormattingRoute = ZhReferenceFormattingRouteImport.update({
  id: '/zh/reference/formatting',
  path: '/zh/reference/formatting',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceFunctionsRoute = ZhReferenceFunctionsRouteImport.update({
  id: '/zh/reference/functions',
  path: '/zh/reference/functions',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceGrammarRoute = ZhReferenceGrammarRouteImport.update({
  id: '/zh/reference/grammar',
  path: '/zh/reference/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceInteropRoute = ZhReferenceInteropRouteImport.update({
  id: '/zh/reference/interop',
  path: '/zh/reference/interop',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceLexicalRoute = ZhReferenceLexicalRouteImport.update({
  id: '/zh/reference/lexical',
  path: '/zh/reference/lexical',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceModulesRoute = ZhReferenceModulesRouteImport.update({
  id: '/zh/reference/modules',
  path: '/zh/reference/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceOwnershipRoute = ZhReferenceOwnershipRouteImport.update({
  id: '/zh/reference/ownership',
  path: '/zh/reference/ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferencePointersRoute = ZhReferencePointersRouteImport.update({
  id: '/zh/reference/pointers',
  path: '/zh/reference/pointers',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceSlicesRoute = ZhReferenceSlicesRouteImport.update({
  id: '/zh/reference/slices',
  path: '/zh/reference/slices',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceTextRoute = ZhReferenceTextRouteImport.update({
  id: '/zh/reference/text',
  path: '/zh/reference/text',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceToolchainRoute = ZhReferenceToolchainRouteImport.update({
  id: '/zh/reference/toolchain',
  path: '/zh/reference/toolchain',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceTypesRoute = ZhReferenceTypesRouteImport.update({
  id: '/zh/reference/types',
  path: '/zh/reference/types',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReferenceUtfRoute = ZhReferenceUtfRouteImport.update({
  id: '/zh/reference/utf',
  path: '/zh/reference/utf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/philosophy': typeof PhilosophyRoute
  '/use-cases': typeof UseCasesRoute
  '/features/compile-time': typeof FeaturesCompileTimeRoute
  '/features/cpp-generation': typeof FeaturesCppGenerationRoute
  '/features/failure-contracts': typeof FeaturesFailureContractsRoute
  '/learn/aggregates': typeof LearnAggregatesRoute
  '/learn/closures': typeof LearnClosuresRoute
  '/learn/constants': typeof LearnConstantsRoute
  '/learn/control': typeof LearnControlRoute
  '/learn/failures': typeof LearnFailuresRoute
  '/learn/formatting': typeof LearnFormattingRoute
  '/learn/functions': typeof LearnFunctionsRoute
  '/learn/interop': typeof LearnInteropRoute
  '/learn/modules': typeof LearnModulesRoute
  '/learn/ownership': typeof LearnOwnershipRoute
  '/learn/pointers': typeof LearnPointersRoute
  '/learn/project': typeof LearnProjectRoute
  '/learn/testing': typeof LearnTestingRoute
  '/learn/text': typeof LearnTextRoute
  '/learn/values': typeof LearnValuesRoute
  '/learn/workflow': typeof LearnWorkflowRoute
  '/reference/aggregates': typeof ReferenceAggregatesRoute
  '/reference/cli': typeof ReferenceCliRoute
  '/reference/closures': typeof ReferenceClosuresRoute
  '/reference/constants': typeof ReferenceConstantsRoute
  '/reference/control': typeof ReferenceControlRoute
  '/reference/diagnostics': typeof ReferenceDiagnosticsRoute
  '/reference/entry-testing': typeof ReferenceEntryTestingRoute
  '/reference/failures': typeof ReferenceFailuresRoute
  '/reference/formatting': typeof ReferenceFormattingRoute
  '/reference/functions': typeof ReferenceFunctionsRoute
  '/reference/grammar': typeof ReferenceGrammarRoute
  '/reference/interop': typeof ReferenceInteropRoute
  '/reference/lexical': typeof ReferenceLexicalRoute
  '/reference/modules': typeof ReferenceModulesRoute
  '/reference/ownership': typeof ReferenceOwnershipRoute
  '/reference/pointers': typeof ReferencePointersRoute
  '/reference/slices': typeof ReferenceSlicesRoute
  '/reference/text': typeof ReferenceTextRoute
  '/reference/toolchain': typeof ReferenceToolchainRoute
  '/reference/types': typeof ReferenceTypesRoute
  '/reference/utf': typeof ReferenceUtfRoute
  '/zh/404': typeof Zh404Route
  '/zh/philosophy': typeof ZhPhilosophyRoute
  '/zh/use-cases': typeof ZhUseCasesRoute
  '/learn/': typeof LearnIndexRoute
  '/reference/': typeof ReferenceIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/zh/features/compile-time': typeof ZhFeaturesCompileTimeRoute
  '/zh/features/cpp-generation': typeof ZhFeaturesCppGenerationRoute
  '/zh/features/failure-contracts': typeof ZhFeaturesFailureContractsRoute
  '/zh/learn/aggregates': typeof ZhLearnAggregatesRoute
  '/zh/learn/closures': typeof ZhLearnClosuresRoute
  '/zh/learn/constants': typeof ZhLearnConstantsRoute
  '/zh/learn/control': typeof ZhLearnControlRoute
  '/zh/learn/failures': typeof ZhLearnFailuresRoute
  '/zh/learn/formatting': typeof ZhLearnFormattingRoute
  '/zh/learn/functions': typeof ZhLearnFunctionsRoute
  '/zh/learn/interop': typeof ZhLearnInteropRoute
  '/zh/learn/modules': typeof ZhLearnModulesRoute
  '/zh/learn/ownership': typeof ZhLearnOwnershipRoute
  '/zh/learn/pointers': typeof ZhLearnPointersRoute
  '/zh/learn/project': typeof ZhLearnProjectRoute
  '/zh/learn/testing': typeof ZhLearnTestingRoute
  '/zh/learn/text': typeof ZhLearnTextRoute
  '/zh/learn/values': typeof ZhLearnValuesRoute
  '/zh/learn/workflow': typeof ZhLearnWorkflowRoute
  '/zh/reference/aggregates': typeof ZhReferenceAggregatesRoute
  '/zh/reference/cli': typeof ZhReferenceCliRoute
  '/zh/reference/closures': typeof ZhReferenceClosuresRoute
  '/zh/reference/constants': typeof ZhReferenceConstantsRoute
  '/zh/reference/control': typeof ZhReferenceControlRoute
  '/zh/reference/diagnostics': typeof ZhReferenceDiagnosticsRoute
  '/zh/reference/entry-testing': typeof ZhReferenceEntryTestingRoute
  '/zh/reference/failures': typeof ZhReferenceFailuresRoute
  '/zh/reference/formatting': typeof ZhReferenceFormattingRoute
  '/zh/reference/functions': typeof ZhReferenceFunctionsRoute
  '/zh/reference/grammar': typeof ZhReferenceGrammarRoute
  '/zh/reference/interop': typeof ZhReferenceInteropRoute
  '/zh/reference/lexical': typeof ZhReferenceLexicalRoute
  '/zh/reference/modules': typeof ZhReferenceModulesRoute
  '/zh/reference/ownership': typeof ZhReferenceOwnershipRoute
  '/zh/reference/pointers': typeof ZhReferencePointersRoute
  '/zh/reference/slices': typeof ZhReferenceSlicesRoute
  '/zh/reference/text': typeof ZhReferenceTextRoute
  '/zh/reference/toolchain': typeof ZhReferenceToolchainRoute
  '/zh/reference/types': typeof ZhReferenceTypesRoute
  '/zh/reference/utf': typeof ZhReferenceUtfRoute
  '/zh/learn/': typeof ZhLearnIndexRoute
  '/zh/reference/': typeof ZhReferenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/philosophy': typeof PhilosophyRoute
  '/use-cases': typeof UseCasesRoute
  '/features/compile-time': typeof FeaturesCompileTimeRoute
  '/features/cpp-generation': typeof FeaturesCppGenerationRoute
  '/features/failure-contracts': typeof FeaturesFailureContractsRoute
  '/learn/aggregates': typeof LearnAggregatesRoute
  '/learn/closures': typeof LearnClosuresRoute
  '/learn/constants': typeof LearnConstantsRoute
  '/learn/control': typeof LearnControlRoute
  '/learn/failures': typeof LearnFailuresRoute
  '/learn/formatting': typeof LearnFormattingRoute
  '/learn/functions': typeof LearnFunctionsRoute
  '/learn/interop': typeof LearnInteropRoute
  '/learn/modules': typeof LearnModulesRoute
  '/learn/ownership': typeof LearnOwnershipRoute
  '/learn/pointers': typeof LearnPointersRoute
  '/learn/project': typeof LearnProjectRoute
  '/learn/testing': typeof LearnTestingRoute
  '/learn/text': typeof LearnTextRoute
  '/learn/values': typeof LearnValuesRoute
  '/learn/workflow': typeof LearnWorkflowRoute
  '/reference/aggregates': typeof ReferenceAggregatesRoute
  '/reference/cli': typeof ReferenceCliRoute
  '/reference/closures': typeof ReferenceClosuresRoute
  '/reference/constants': typeof ReferenceConstantsRoute
  '/reference/control': typeof ReferenceControlRoute
  '/reference/diagnostics': typeof ReferenceDiagnosticsRoute
  '/reference/entry-testing': typeof ReferenceEntryTestingRoute
  '/reference/failures': typeof ReferenceFailuresRoute
  '/reference/formatting': typeof ReferenceFormattingRoute
  '/reference/functions': typeof ReferenceFunctionsRoute
  '/reference/grammar': typeof ReferenceGrammarRoute
  '/reference/interop': typeof ReferenceInteropRoute
  '/reference/lexical': typeof ReferenceLexicalRoute
  '/reference/modules': typeof ReferenceModulesRoute
  '/reference/ownership': typeof ReferenceOwnershipRoute
  '/reference/pointers': typeof ReferencePointersRoute
  '/reference/slices': typeof ReferenceSlicesRoute
  '/reference/text': typeof ReferenceTextRoute
  '/reference/toolchain': typeof ReferenceToolchainRoute
  '/reference/types': typeof ReferenceTypesRoute
  '/reference/utf': typeof ReferenceUtfRoute
  '/zh/404': typeof Zh404Route
  '/zh/philosophy': typeof ZhPhilosophyRoute
  '/zh/use-cases': typeof ZhUseCasesRoute
  '/learn': typeof LearnIndexRoute
  '/reference': typeof ReferenceIndexRoute
  '/zh': typeof ZhIndexRoute
  '/zh/features/compile-time': typeof ZhFeaturesCompileTimeRoute
  '/zh/features/cpp-generation': typeof ZhFeaturesCppGenerationRoute
  '/zh/features/failure-contracts': typeof ZhFeaturesFailureContractsRoute
  '/zh/learn/aggregates': typeof ZhLearnAggregatesRoute
  '/zh/learn/closures': typeof ZhLearnClosuresRoute
  '/zh/learn/constants': typeof ZhLearnConstantsRoute
  '/zh/learn/control': typeof ZhLearnControlRoute
  '/zh/learn/failures': typeof ZhLearnFailuresRoute
  '/zh/learn/formatting': typeof ZhLearnFormattingRoute
  '/zh/learn/functions': typeof ZhLearnFunctionsRoute
  '/zh/learn/interop': typeof ZhLearnInteropRoute
  '/zh/learn/modules': typeof ZhLearnModulesRoute
  '/zh/learn/ownership': typeof ZhLearnOwnershipRoute
  '/zh/learn/pointers': typeof ZhLearnPointersRoute
  '/zh/learn/project': typeof ZhLearnProjectRoute
  '/zh/learn/testing': typeof ZhLearnTestingRoute
  '/zh/learn/text': typeof ZhLearnTextRoute
  '/zh/learn/values': typeof ZhLearnValuesRoute
  '/zh/learn/workflow': typeof ZhLearnWorkflowRoute
  '/zh/reference/aggregates': typeof ZhReferenceAggregatesRoute
  '/zh/reference/cli': typeof ZhReferenceCliRoute
  '/zh/reference/closures': typeof ZhReferenceClosuresRoute
  '/zh/reference/constants': typeof ZhReferenceConstantsRoute
  '/zh/reference/control': typeof ZhReferenceControlRoute
  '/zh/reference/diagnostics': typeof ZhReferenceDiagnosticsRoute
  '/zh/reference/entry-testing': typeof ZhReferenceEntryTestingRoute
  '/zh/reference/failures': typeof ZhReferenceFailuresRoute
  '/zh/reference/formatting': typeof ZhReferenceFormattingRoute
  '/zh/reference/functions': typeof ZhReferenceFunctionsRoute
  '/zh/reference/grammar': typeof ZhReferenceGrammarRoute
  '/zh/reference/interop': typeof ZhReferenceInteropRoute
  '/zh/reference/lexical': typeof ZhReferenceLexicalRoute
  '/zh/reference/modules': typeof ZhReferenceModulesRoute
  '/zh/reference/ownership': typeof ZhReferenceOwnershipRoute
  '/zh/reference/pointers': typeof ZhReferencePointersRoute
  '/zh/reference/slices': typeof ZhReferenceSlicesRoute
  '/zh/reference/text': typeof ZhReferenceTextRoute
  '/zh/reference/toolchain': typeof ZhReferenceToolchainRoute
  '/zh/reference/types': typeof ZhReferenceTypesRoute
  '/zh/reference/utf': typeof ZhReferenceUtfRoute
  '/zh/learn': typeof ZhLearnIndexRoute
  '/zh/reference': typeof ZhReferenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/philosophy': typeof PhilosophyRoute
  '/use-cases': typeof UseCasesRoute
  '/features/compile-time': typeof FeaturesCompileTimeRoute
  '/features/cpp-generation': typeof FeaturesCppGenerationRoute
  '/features/failure-contracts': typeof FeaturesFailureContractsRoute
  '/learn/aggregates': typeof LearnAggregatesRoute
  '/learn/closures': typeof LearnClosuresRoute
  '/learn/constants': typeof LearnConstantsRoute
  '/learn/control': typeof LearnControlRoute
  '/learn/failures': typeof LearnFailuresRoute
  '/learn/formatting': typeof LearnFormattingRoute
  '/learn/functions': typeof LearnFunctionsRoute
  '/learn/interop': typeof LearnInteropRoute
  '/learn/modules': typeof LearnModulesRoute
  '/learn/ownership': typeof LearnOwnershipRoute
  '/learn/pointers': typeof LearnPointersRoute
  '/learn/project': typeof LearnProjectRoute
  '/learn/testing': typeof LearnTestingRoute
  '/learn/text': typeof LearnTextRoute
  '/learn/values': typeof LearnValuesRoute
  '/learn/workflow': typeof LearnWorkflowRoute
  '/reference/aggregates': typeof ReferenceAggregatesRoute
  '/reference/cli': typeof ReferenceCliRoute
  '/reference/closures': typeof ReferenceClosuresRoute
  '/reference/constants': typeof ReferenceConstantsRoute
  '/reference/control': typeof ReferenceControlRoute
  '/reference/diagnostics': typeof ReferenceDiagnosticsRoute
  '/reference/entry-testing': typeof ReferenceEntryTestingRoute
  '/reference/failures': typeof ReferenceFailuresRoute
  '/reference/formatting': typeof ReferenceFormattingRoute
  '/reference/functions': typeof ReferenceFunctionsRoute
  '/reference/grammar': typeof ReferenceGrammarRoute
  '/reference/interop': typeof ReferenceInteropRoute
  '/reference/lexical': typeof ReferenceLexicalRoute
  '/reference/modules': typeof ReferenceModulesRoute
  '/reference/ownership': typeof ReferenceOwnershipRoute
  '/reference/pointers': typeof ReferencePointersRoute
  '/reference/slices': typeof ReferenceSlicesRoute
  '/reference/text': typeof ReferenceTextRoute
  '/reference/toolchain': typeof ReferenceToolchainRoute
  '/reference/types': typeof ReferenceTypesRoute
  '/reference/utf': typeof ReferenceUtfRoute
  '/zh/404': typeof Zh404Route
  '/zh/philosophy': typeof ZhPhilosophyRoute
  '/zh/use-cases': typeof ZhUseCasesRoute
  '/learn/': typeof LearnIndexRoute
  '/reference/': typeof ReferenceIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/zh/features/compile-time': typeof ZhFeaturesCompileTimeRoute
  '/zh/features/cpp-generation': typeof ZhFeaturesCppGenerationRoute
  '/zh/features/failure-contracts': typeof ZhFeaturesFailureContractsRoute
  '/zh/learn/aggregates': typeof ZhLearnAggregatesRoute
  '/zh/learn/closures': typeof ZhLearnClosuresRoute
  '/zh/learn/constants': typeof ZhLearnConstantsRoute
  '/zh/learn/control': typeof ZhLearnControlRoute
  '/zh/learn/failures': typeof ZhLearnFailuresRoute
  '/zh/learn/formatting': typeof ZhLearnFormattingRoute
  '/zh/learn/functions': typeof ZhLearnFunctionsRoute
  '/zh/learn/interop': typeof ZhLearnInteropRoute
  '/zh/learn/modules': typeof ZhLearnModulesRoute
  '/zh/learn/ownership': typeof ZhLearnOwnershipRoute
  '/zh/learn/pointers': typeof ZhLearnPointersRoute
  '/zh/learn/project': typeof ZhLearnProjectRoute
  '/zh/learn/testing': typeof ZhLearnTestingRoute
  '/zh/learn/text': typeof ZhLearnTextRoute
  '/zh/learn/values': typeof ZhLearnValuesRoute
  '/zh/learn/workflow': typeof ZhLearnWorkflowRoute
  '/zh/reference/aggregates': typeof ZhReferenceAggregatesRoute
  '/zh/reference/cli': typeof ZhReferenceCliRoute
  '/zh/reference/closures': typeof ZhReferenceClosuresRoute
  '/zh/reference/constants': typeof ZhReferenceConstantsRoute
  '/zh/reference/control': typeof ZhReferenceControlRoute
  '/zh/reference/diagnostics': typeof ZhReferenceDiagnosticsRoute
  '/zh/reference/entry-testing': typeof ZhReferenceEntryTestingRoute
  '/zh/reference/failures': typeof ZhReferenceFailuresRoute
  '/zh/reference/formatting': typeof ZhReferenceFormattingRoute
  '/zh/reference/functions': typeof ZhReferenceFunctionsRoute
  '/zh/reference/grammar': typeof ZhReferenceGrammarRoute
  '/zh/reference/interop': typeof ZhReferenceInteropRoute
  '/zh/reference/lexical': typeof ZhReferenceLexicalRoute
  '/zh/reference/modules': typeof ZhReferenceModulesRoute
  '/zh/reference/ownership': typeof ZhReferenceOwnershipRoute
  '/zh/reference/pointers': typeof ZhReferencePointersRoute
  '/zh/reference/slices': typeof ZhReferenceSlicesRoute
  '/zh/reference/text': typeof ZhReferenceTextRoute
  '/zh/reference/toolchain': typeof ZhReferenceToolchainRoute
  '/zh/reference/types': typeof ZhReferenceTypesRoute
  '/zh/reference/utf': typeof ZhReferenceUtfRoute
  '/zh/learn/': typeof ZhLearnIndexRoute
  '/zh/reference/': typeof ZhReferenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/philosophy'
    | '/use-cases'
    | '/features/compile-time'
    | '/features/cpp-generation'
    | '/features/failure-contracts'
    | '/learn/aggregates'
    | '/learn/closures'
    | '/learn/constants'
    | '/learn/control'
    | '/learn/failures'
    | '/learn/formatting'
    | '/learn/functions'
    | '/learn/interop'
    | '/learn/modules'
    | '/learn/ownership'
    | '/learn/pointers'
    | '/learn/project'
    | '/learn/testing'
    | '/learn/text'
    | '/learn/values'
    | '/learn/workflow'
    | '/reference/aggregates'
    | '/reference/cli'
    | '/reference/closures'
    | '/reference/constants'
    | '/reference/control'
    | '/reference/diagnostics'
    | '/reference/entry-testing'
    | '/reference/failures'
    | '/reference/formatting'
    | '/reference/functions'
    | '/reference/grammar'
    | '/reference/interop'
    | '/reference/lexical'
    | '/reference/modules'
    | '/reference/ownership'
    | '/reference/pointers'
    | '/reference/slices'
    | '/reference/text'
    | '/reference/toolchain'
    | '/reference/types'
    | '/reference/utf'
    | '/zh/404'
    | '/zh/philosophy'
    | '/zh/use-cases'
    | '/learn/'
    | '/reference/'
    | '/zh/'
    | '/zh/features/compile-time'
    | '/zh/features/cpp-generation'
    | '/zh/features/failure-contracts'
    | '/zh/learn/aggregates'
    | '/zh/learn/closures'
    | '/zh/learn/constants'
    | '/zh/learn/control'
    | '/zh/learn/failures'
    | '/zh/learn/formatting'
    | '/zh/learn/functions'
    | '/zh/learn/interop'
    | '/zh/learn/modules'
    | '/zh/learn/ownership'
    | '/zh/learn/pointers'
    | '/zh/learn/project'
    | '/zh/learn/testing'
    | '/zh/learn/text'
    | '/zh/learn/values'
    | '/zh/learn/workflow'
    | '/zh/reference/aggregates'
    | '/zh/reference/cli'
    | '/zh/reference/closures'
    | '/zh/reference/constants'
    | '/zh/reference/control'
    | '/zh/reference/diagnostics'
    | '/zh/reference/entry-testing'
    | '/zh/reference/failures'
    | '/zh/reference/formatting'
    | '/zh/reference/functions'
    | '/zh/reference/grammar'
    | '/zh/reference/interop'
    | '/zh/reference/lexical'
    | '/zh/reference/modules'
    | '/zh/reference/ownership'
    | '/zh/reference/pointers'
    | '/zh/reference/slices'
    | '/zh/reference/text'
    | '/zh/reference/toolchain'
    | '/zh/reference/types'
    | '/zh/reference/utf'
    | '/zh/learn/'
    | '/zh/reference/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/philosophy'
    | '/use-cases'
    | '/features/compile-time'
    | '/features/cpp-generation'
    | '/features/failure-contracts'
    | '/learn/aggregates'
    | '/learn/closures'
    | '/learn/constants'
    | '/learn/control'
    | '/learn/failures'
    | '/learn/formatting'
    | '/learn/functions'
    | '/learn/interop'
    | '/learn/modules'
    | '/learn/ownership'
    | '/learn/pointers'
    | '/learn/project'
    | '/learn/testing'
    | '/learn/text'
    | '/learn/values'
    | '/learn/workflow'
    | '/reference/aggregates'
    | '/reference/cli'
    | '/reference/closures'
    | '/reference/constants'
    | '/reference/control'
    | '/reference/diagnostics'
    | '/reference/entry-testing'
    | '/reference/failures'
    | '/reference/formatting'
    | '/reference/functions'
    | '/reference/grammar'
    | '/reference/interop'
    | '/reference/lexical'
    | '/reference/modules'
    | '/reference/ownership'
    | '/reference/pointers'
    | '/reference/slices'
    | '/reference/text'
    | '/reference/toolchain'
    | '/reference/types'
    | '/reference/utf'
    | '/zh/404'
    | '/zh/philosophy'
    | '/zh/use-cases'
    | '/learn'
    | '/reference'
    | '/zh'
    | '/zh/features/compile-time'
    | '/zh/features/cpp-generation'
    | '/zh/features/failure-contracts'
    | '/zh/learn/aggregates'
    | '/zh/learn/closures'
    | '/zh/learn/constants'
    | '/zh/learn/control'
    | '/zh/learn/failures'
    | '/zh/learn/formatting'
    | '/zh/learn/functions'
    | '/zh/learn/interop'
    | '/zh/learn/modules'
    | '/zh/learn/ownership'
    | '/zh/learn/pointers'
    | '/zh/learn/project'
    | '/zh/learn/testing'
    | '/zh/learn/text'
    | '/zh/learn/values'
    | '/zh/learn/workflow'
    | '/zh/reference/aggregates'
    | '/zh/reference/cli'
    | '/zh/reference/closures'
    | '/zh/reference/constants'
    | '/zh/reference/control'
    | '/zh/reference/diagnostics'
    | '/zh/reference/entry-testing'
    | '/zh/reference/failures'
    | '/zh/reference/formatting'
    | '/zh/reference/functions'
    | '/zh/reference/grammar'
    | '/zh/reference/interop'
    | '/zh/reference/lexical'
    | '/zh/reference/modules'
    | '/zh/reference/ownership'
    | '/zh/reference/pointers'
    | '/zh/reference/slices'
    | '/zh/reference/text'
    | '/zh/reference/toolchain'
    | '/zh/reference/types'
    | '/zh/reference/utf'
    | '/zh/learn'
    | '/zh/reference'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/philosophy'
    | '/use-cases'
    | '/features/compile-time'
    | '/features/cpp-generation'
    | '/features/failure-contracts'
    | '/learn/aggregates'
    | '/learn/closures'
    | '/learn/constants'
    | '/learn/control'
    | '/learn/failures'
    | '/learn/formatting'
    | '/learn/functions'
    | '/learn/interop'
    | '/learn/modules'
    | '/learn/ownership'
    | '/learn/pointers'
    | '/learn/project'
    | '/learn/testing'
    | '/learn/text'
    | '/learn/values'
    | '/learn/workflow'
    | '/reference/aggregates'
    | '/reference/cli'
    | '/reference/closures'
    | '/reference/constants'
    | '/reference/control'
    | '/reference/diagnostics'
    | '/reference/entry-testing'
    | '/reference/failures'
    | '/reference/formatting'
    | '/reference/functions'
    | '/reference/grammar'
    | '/reference/interop'
    | '/reference/lexical'
    | '/reference/modules'
    | '/reference/ownership'
    | '/reference/pointers'
    | '/reference/slices'
    | '/reference/text'
    | '/reference/toolchain'
    | '/reference/types'
    | '/reference/utf'
    | '/zh/404'
    | '/zh/philosophy'
    | '/zh/use-cases'
    | '/learn/'
    | '/reference/'
    | '/zh/'
    | '/zh/features/compile-time'
    | '/zh/features/cpp-generation'
    | '/zh/features/failure-contracts'
    | '/zh/learn/aggregates'
    | '/zh/learn/closures'
    | '/zh/learn/constants'
    | '/zh/learn/control'
    | '/zh/learn/failures'
    | '/zh/learn/formatting'
    | '/zh/learn/functions'
    | '/zh/learn/interop'
    | '/zh/learn/modules'
    | '/zh/learn/ownership'
    | '/zh/learn/pointers'
    | '/zh/learn/project'
    | '/zh/learn/testing'
    | '/zh/learn/text'
    | '/zh/learn/values'
    | '/zh/learn/workflow'
    | '/zh/reference/aggregates'
    | '/zh/reference/cli'
    | '/zh/reference/closures'
    | '/zh/reference/constants'
    | '/zh/reference/control'
    | '/zh/reference/diagnostics'
    | '/zh/reference/entry-testing'
    | '/zh/reference/failures'
    | '/zh/reference/formatting'
    | '/zh/reference/functions'
    | '/zh/reference/grammar'
    | '/zh/reference/interop'
    | '/zh/reference/lexical'
    | '/zh/reference/modules'
    | '/zh/reference/ownership'
    | '/zh/reference/pointers'
    | '/zh/reference/slices'
    | '/zh/reference/text'
    | '/zh/reference/toolchain'
    | '/zh/reference/types'
    | '/zh/reference/utf'
    | '/zh/learn/'
    | '/zh/reference/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  PhilosophyRoute: typeof PhilosophyRoute
  UseCasesRoute: typeof UseCasesRoute
  FeaturesCompileTimeRoute: typeof FeaturesCompileTimeRoute
  FeaturesCppGenerationRoute: typeof FeaturesCppGenerationRoute
  FeaturesFailureContractsRoute: typeof FeaturesFailureContractsRoute
  LearnAggregatesRoute: typeof LearnAggregatesRoute
  LearnClosuresRoute: typeof LearnClosuresRoute
  LearnConstantsRoute: typeof LearnConstantsRoute
  LearnControlRoute: typeof LearnControlRoute
  LearnFailuresRoute: typeof LearnFailuresRoute
  LearnFormattingRoute: typeof LearnFormattingRoute
  LearnFunctionsRoute: typeof LearnFunctionsRoute
  LearnInteropRoute: typeof LearnInteropRoute
  LearnModulesRoute: typeof LearnModulesRoute
  LearnOwnershipRoute: typeof LearnOwnershipRoute
  LearnPointersRoute: typeof LearnPointersRoute
  LearnProjectRoute: typeof LearnProjectRoute
  LearnTestingRoute: typeof LearnTestingRoute
  LearnTextRoute: typeof LearnTextRoute
  LearnValuesRoute: typeof LearnValuesRoute
  LearnWorkflowRoute: typeof LearnWorkflowRoute
  ReferenceAggregatesRoute: typeof ReferenceAggregatesRoute
  ReferenceCliRoute: typeof ReferenceCliRoute
  ReferenceClosuresRoute: typeof ReferenceClosuresRoute
  ReferenceConstantsRoute: typeof ReferenceConstantsRoute
  ReferenceControlRoute: typeof ReferenceControlRoute
  ReferenceDiagnosticsRoute: typeof ReferenceDiagnosticsRoute
  ReferenceEntryTestingRoute: typeof ReferenceEntryTestingRoute
  ReferenceFailuresRoute: typeof ReferenceFailuresRoute
  ReferenceFormattingRoute: typeof ReferenceFormattingRoute
  ReferenceFunctionsRoute: typeof ReferenceFunctionsRoute
  ReferenceGrammarRoute: typeof ReferenceGrammarRoute
  ReferenceInteropRoute: typeof ReferenceInteropRoute
  ReferenceLexicalRoute: typeof ReferenceLexicalRoute
  ReferenceModulesRoute: typeof ReferenceModulesRoute
  ReferenceOwnershipRoute: typeof ReferenceOwnershipRoute
  ReferencePointersRoute: typeof ReferencePointersRoute
  ReferenceSlicesRoute: typeof ReferenceSlicesRoute
  ReferenceTextRoute: typeof ReferenceTextRoute
  ReferenceToolchainRoute: typeof ReferenceToolchainRoute
  ReferenceTypesRoute: typeof ReferenceTypesRoute
  ReferenceUtfRoute: typeof ReferenceUtfRoute
  Zh404Route: typeof Zh404Route
  ZhPhilosophyRoute: typeof ZhPhilosophyRoute
  ZhUseCasesRoute: typeof ZhUseCasesRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ReferenceIndexRoute: typeof ReferenceIndexRoute
  ZhIndexRoute: typeof ZhIndexRoute
  ZhFeaturesCompileTimeRoute: typeof ZhFeaturesCompileTimeRoute
  ZhFeaturesCppGenerationRoute: typeof ZhFeaturesCppGenerationRoute
  ZhFeaturesFailureContractsRoute: typeof ZhFeaturesFailureContractsRoute
  ZhLearnAggregatesRoute: typeof ZhLearnAggregatesRoute
  ZhLearnClosuresRoute: typeof ZhLearnClosuresRoute
  ZhLearnConstantsRoute: typeof ZhLearnConstantsRoute
  ZhLearnControlRoute: typeof ZhLearnControlRoute
  ZhLearnFailuresRoute: typeof ZhLearnFailuresRoute
  ZhLearnFormattingRoute: typeof ZhLearnFormattingRoute
  ZhLearnFunctionsRoute: typeof ZhLearnFunctionsRoute
  ZhLearnInteropRoute: typeof ZhLearnInteropRoute
  ZhLearnModulesRoute: typeof ZhLearnModulesRoute
  ZhLearnOwnershipRoute: typeof ZhLearnOwnershipRoute
  ZhLearnPointersRoute: typeof ZhLearnPointersRoute
  ZhLearnProjectRoute: typeof ZhLearnProjectRoute
  ZhLearnTestingRoute: typeof ZhLearnTestingRoute
  ZhLearnTextRoute: typeof ZhLearnTextRoute
  ZhLearnValuesRoute: typeof ZhLearnValuesRoute
  ZhLearnWorkflowRoute: typeof ZhLearnWorkflowRoute
  ZhReferenceAggregatesRoute: typeof ZhReferenceAggregatesRoute
  ZhReferenceCliRoute: typeof ZhReferenceCliRoute
  ZhReferenceClosuresRoute: typeof ZhReferenceClosuresRoute
  ZhReferenceConstantsRoute: typeof ZhReferenceConstantsRoute
  ZhReferenceControlRoute: typeof ZhReferenceControlRoute
  ZhReferenceDiagnosticsRoute: typeof ZhReferenceDiagnosticsRoute
  ZhReferenceEntryTestingRoute: typeof ZhReferenceEntryTestingRoute
  ZhReferenceFailuresRoute: typeof ZhReferenceFailuresRoute
  ZhReferenceFormattingRoute: typeof ZhReferenceFormattingRoute
  ZhReferenceFunctionsRoute: typeof ZhReferenceFunctionsRoute
  ZhReferenceGrammarRoute: typeof ZhReferenceGrammarRoute
  ZhReferenceInteropRoute: typeof ZhReferenceInteropRoute
  ZhReferenceLexicalRoute: typeof ZhReferenceLexicalRoute
  ZhReferenceModulesRoute: typeof ZhReferenceModulesRoute
  ZhReferenceOwnershipRoute: typeof ZhReferenceOwnershipRoute
  ZhReferencePointersRoute: typeof ZhReferencePointersRoute
  ZhReferenceSlicesRoute: typeof ZhReferenceSlicesRoute
  ZhReferenceTextRoute: typeof ZhReferenceTextRoute
  ZhReferenceToolchainRoute: typeof ZhReferenceToolchainRoute
  ZhReferenceTypesRoute: typeof ZhReferenceTypesRoute
  ZhReferenceUtfRoute: typeof ZhReferenceUtfRoute
  ZhLearnIndexRoute: typeof ZhLearnIndexRoute
  ZhReferenceIndexRoute: typeof ZhReferenceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/compile-time': {
      id: '/features/compile-time'
      path: '/features/compile-time'
      fullPath: '/features/compile-time'
      preLoaderRoute: typeof FeaturesCompileTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/cpp-generation': {
      id: '/features/cpp-generation'
      path: '/features/cpp-generation'
      fullPath: '/features/cpp-generation'
      preLoaderRoute: typeof FeaturesCppGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/failure-contracts': {
      id: '/features/failure-contracts'
      path: '/features/failure-contracts'
      fullPath: '/features/failure-contracts'
      preLoaderRoute: typeof FeaturesFailureContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/aggregates': {
      id: '/learn/aggregates'
      path: '/learn/aggregates'
      fullPath: '/learn/aggregates'
      preLoaderRoute: typeof LearnAggregatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/closures': {
      id: '/learn/closures'
      path: '/learn/closures'
      fullPath: '/learn/closures'
      preLoaderRoute: typeof LearnClosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/constants': {
      id: '/learn/constants'
      path: '/learn/constants'
      fullPath: '/learn/constants'
      preLoaderRoute: typeof LearnConstantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/control': {
      id: '/learn/control'
      path: '/learn/control'
      fullPath: '/learn/control'
      preLoaderRoute: typeof LearnControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/failures': {
      id: '/learn/failures'
      path: '/learn/failures'
      fullPath: '/learn/failures'
      preLoaderRoute: typeof LearnFailuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/formatting': {
      id: '/learn/formatting'
      path: '/learn/formatting'
      fullPath: '/learn/formatting'
      preLoaderRoute: typeof LearnFormattingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/functions': {
      id: '/learn/functions'
      path: '/learn/functions'
      fullPath: '/learn/functions'
      preLoaderRoute: typeof LearnFunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/interop': {
      id: '/learn/interop'
      path: '/learn/interop'
      fullPath: '/learn/interop'
      preLoaderRoute: typeof LearnInteropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/modules': {
      id: '/learn/modules'
      path: '/learn/modules'
      fullPath: '/learn/modules'
      preLoaderRoute: typeof LearnModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/ownership': {
      id: '/learn/ownership'
      path: '/learn/ownership'
      fullPath: '/learn/ownership'
      preLoaderRoute: typeof LearnOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/pointers': {
      id: '/learn/pointers'
      path: '/learn/pointers'
      fullPath: '/learn/pointers'
      preLoaderRoute: typeof LearnPointersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/project': {
      id: '/learn/project'
      path: '/learn/project'
      fullPath: '/learn/project'
      preLoaderRoute: typeof LearnProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/testing': {
      id: '/learn/testing'
      path: '/learn/testing'
      fullPath: '/learn/testing'
      preLoaderRoute: typeof LearnTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/text': {
      id: '/learn/text'
      path: '/learn/text'
      fullPath: '/learn/text'
      preLoaderRoute: typeof LearnTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/values': {
      id: '/learn/values'
      path: '/learn/values'
      fullPath: '/learn/values'
      preLoaderRoute: typeof LearnValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/workflow': {
      id: '/learn/workflow'
      path: '/learn/workflow'
      fullPath: '/learn/workflow'
      preLoaderRoute: typeof LearnWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/': {
      id: '/reference/'
      path: '/reference'
      fullPath: '/reference/'
      preLoaderRoute: typeof ReferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/aggregates': {
      id: '/reference/aggregates'
      path: '/reference/aggregates'
      fullPath: '/reference/aggregates'
      preLoaderRoute: typeof ReferenceAggregatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/cli': {
      id: '/reference/cli'
      path: '/reference/cli'
      fullPath: '/reference/cli'
      preLoaderRoute: typeof ReferenceCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/closures': {
      id: '/reference/closures'
      path: '/reference/closures'
      fullPath: '/reference/closures'
      preLoaderRoute: typeof ReferenceClosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/constants': {
      id: '/reference/constants'
      path: '/reference/constants'
      fullPath: '/reference/constants'
      preLoaderRoute: typeof ReferenceConstantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/control': {
      id: '/reference/control'
      path: '/reference/control'
      fullPath: '/reference/control'
      preLoaderRoute: typeof ReferenceControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/diagnostics': {
      id: '/reference/diagnostics'
      path: '/reference/diagnostics'
      fullPath: '/reference/diagnostics'
      preLoaderRoute: typeof ReferenceDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/entry-testing': {
      id: '/reference/entry-testing'
      path: '/reference/entry-testing'
      fullPath: '/reference/entry-testing'
      preLoaderRoute: typeof ReferenceEntryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/failures': {
      id: '/reference/failures'
      path: '/reference/failures'
      fullPath: '/reference/failures'
      preLoaderRoute: typeof ReferenceFailuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/formatting': {
      id: '/reference/formatting'
      path: '/reference/formatting'
      fullPath: '/reference/formatting'
      preLoaderRoute: typeof ReferenceFormattingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/functions': {
      id: '/reference/functions'
      path: '/reference/functions'
      fullPath: '/reference/functions'
      preLoaderRoute: typeof ReferenceFunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/grammar': {
      id: '/reference/grammar'
      path: '/reference/grammar'
      fullPath: '/reference/grammar'
      preLoaderRoute: typeof ReferenceGrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/interop': {
      id: '/reference/interop'
      path: '/reference/interop'
      fullPath: '/reference/interop'
      preLoaderRoute: typeof ReferenceInteropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/lexical': {
      id: '/reference/lexical'
      path: '/reference/lexical'
      fullPath: '/reference/lexical'
      preLoaderRoute: typeof ReferenceLexicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/modules': {
      id: '/reference/modules'
      path: '/reference/modules'
      fullPath: '/reference/modules'
      preLoaderRoute: typeof ReferenceModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/ownership': {
      id: '/reference/ownership'
      path: '/reference/ownership'
      fullPath: '/reference/ownership'
      preLoaderRoute: typeof ReferenceOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/pointers': {
      id: '/reference/pointers'
      path: '/reference/pointers'
      fullPath: '/reference/pointers'
      preLoaderRoute: typeof ReferencePointersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/slices': {
      id: '/reference/slices'
      path: '/reference/slices'
      fullPath: '/reference/slices'
      preLoaderRoute: typeof ReferenceSlicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/text': {
      id: '/reference/text'
      path: '/reference/text'
      fullPath: '/reference/text'
      preLoaderRoute: typeof ReferenceTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/toolchain': {
      id: '/reference/toolchain'
      path: '/reference/toolchain'
      fullPath: '/reference/toolchain'
      preLoaderRoute: typeof ReferenceToolchainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/types': {
      id: '/reference/types'
      path: '/reference/types'
      fullPath: '/reference/types'
      preLoaderRoute: typeof ReferenceTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/utf': {
      id: '/reference/utf'
      path: '/reference/utf'
      fullPath: '/reference/utf'
      preLoaderRoute: typeof ReferenceUtfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/': {
      id: '/zh/'
      path: '/zh'
      fullPath: '/zh/'
      preLoaderRoute: typeof ZhIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/404': {
      id: '/zh/404'
      path: '/zh/404'
      fullPath: '/zh/404'
      preLoaderRoute: typeof Zh404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/philosophy': {
      id: '/zh/philosophy'
      path: '/zh/philosophy'
      fullPath: '/zh/philosophy'
      preLoaderRoute: typeof ZhPhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/use-cases': {
      id: '/zh/use-cases'
      path: '/zh/use-cases'
      fullPath: '/zh/use-cases'
      preLoaderRoute: typeof ZhUseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/features/compile-time': {
      id: '/zh/features/compile-time'
      path: '/zh/features/compile-time'
      fullPath: '/zh/features/compile-time'
      preLoaderRoute: typeof ZhFeaturesCompileTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/features/cpp-generation': {
      id: '/zh/features/cpp-generation'
      path: '/zh/features/cpp-generation'
      fullPath: '/zh/features/cpp-generation'
      preLoaderRoute: typeof ZhFeaturesCppGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/features/failure-contracts': {
      id: '/zh/features/failure-contracts'
      path: '/zh/features/failure-contracts'
      fullPath: '/zh/features/failure-contracts'
      preLoaderRoute: typeof ZhFeaturesFailureContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/': {
      id: '/zh/learn/'
      path: '/zh/learn'
      fullPath: '/zh/learn/'
      preLoaderRoute: typeof ZhLearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/aggregates': {
      id: '/zh/learn/aggregates'
      path: '/zh/learn/aggregates'
      fullPath: '/zh/learn/aggregates'
      preLoaderRoute: typeof ZhLearnAggregatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/closures': {
      id: '/zh/learn/closures'
      path: '/zh/learn/closures'
      fullPath: '/zh/learn/closures'
      preLoaderRoute: typeof ZhLearnClosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/constants': {
      id: '/zh/learn/constants'
      path: '/zh/learn/constants'
      fullPath: '/zh/learn/constants'
      preLoaderRoute: typeof ZhLearnConstantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/control': {
      id: '/zh/learn/control'
      path: '/zh/learn/control'
      fullPath: '/zh/learn/control'
      preLoaderRoute: typeof ZhLearnControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/failures': {
      id: '/zh/learn/failures'
      path: '/zh/learn/failures'
      fullPath: '/zh/learn/failures'
      preLoaderRoute: typeof ZhLearnFailuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/formatting': {
      id: '/zh/learn/formatting'
      path: '/zh/learn/formatting'
      fullPath: '/zh/learn/formatting'
      preLoaderRoute: typeof ZhLearnFormattingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/functions': {
      id: '/zh/learn/functions'
      path: '/zh/learn/functions'
      fullPath: '/zh/learn/functions'
      preLoaderRoute: typeof ZhLearnFunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/interop': {
      id: '/zh/learn/interop'
      path: '/zh/learn/interop'
      fullPath: '/zh/learn/interop'
      preLoaderRoute: typeof ZhLearnInteropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/modules': {
      id: '/zh/learn/modules'
      path: '/zh/learn/modules'
      fullPath: '/zh/learn/modules'
      preLoaderRoute: typeof ZhLearnModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/ownership': {
      id: '/zh/learn/ownership'
      path: '/zh/learn/ownership'
      fullPath: '/zh/learn/ownership'
      preLoaderRoute: typeof ZhLearnOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/pointers': {
      id: '/zh/learn/pointers'
      path: '/zh/learn/pointers'
      fullPath: '/zh/learn/pointers'
      preLoaderRoute: typeof ZhLearnPointersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/project': {
      id: '/zh/learn/project'
      path: '/zh/learn/project'
      fullPath: '/zh/learn/project'
      preLoaderRoute: typeof ZhLearnProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/testing': {
      id: '/zh/learn/testing'
      path: '/zh/learn/testing'
      fullPath: '/zh/learn/testing'
      preLoaderRoute: typeof ZhLearnTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/text': {
      id: '/zh/learn/text'
      path: '/zh/learn/text'
      fullPath: '/zh/learn/text'
      preLoaderRoute: typeof ZhLearnTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/values': {
      id: '/zh/learn/values'
      path: '/zh/learn/values'
      fullPath: '/zh/learn/values'
      preLoaderRoute: typeof ZhLearnValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/learn/workflow': {
      id: '/zh/learn/workflow'
      path: '/zh/learn/workflow'
      fullPath: '/zh/learn/workflow'
      preLoaderRoute: typeof ZhLearnWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/': {
      id: '/zh/reference/'
      path: '/zh/reference'
      fullPath: '/zh/reference/'
      preLoaderRoute: typeof ZhReferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/aggregates': {
      id: '/zh/reference/aggregates'
      path: '/zh/reference/aggregates'
      fullPath: '/zh/reference/aggregates'
      preLoaderRoute: typeof ZhReferenceAggregatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/cli': {
      id: '/zh/reference/cli'
      path: '/zh/reference/cli'
      fullPath: '/zh/reference/cli'
      preLoaderRoute: typeof ZhReferenceCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/closures': {
      id: '/zh/reference/closures'
      path: '/zh/reference/closures'
      fullPath: '/zh/reference/closures'
      preLoaderRoute: typeof ZhReferenceClosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/constants': {
      id: '/zh/reference/constants'
      path: '/zh/reference/constants'
      fullPath: '/zh/reference/constants'
      preLoaderRoute: typeof ZhReferenceConstantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/control': {
      id: '/zh/reference/control'
      path: '/zh/reference/control'
      fullPath: '/zh/reference/control'
      preLoaderRoute: typeof ZhReferenceControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/diagnostics': {
      id: '/zh/reference/diagnostics'
      path: '/zh/reference/diagnostics'
      fullPath: '/zh/reference/diagnostics'
      preLoaderRoute: typeof ZhReferenceDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/entry-testing': {
      id: '/zh/reference/entry-testing'
      path: '/zh/reference/entry-testing'
      fullPath: '/zh/reference/entry-testing'
      preLoaderRoute: typeof ZhReferenceEntryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/failures': {
      id: '/zh/reference/failures'
      path: '/zh/reference/failures'
      fullPath: '/zh/reference/failures'
      preLoaderRoute: typeof ZhReferenceFailuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/formatting': {
      id: '/zh/reference/formatting'
      path: '/zh/reference/formatting'
      fullPath: '/zh/reference/formatting'
      preLoaderRoute: typeof ZhReferenceFormattingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/functions': {
      id: '/zh/reference/functions'
      path: '/zh/reference/functions'
      fullPath: '/zh/reference/functions'
      preLoaderRoute: typeof ZhReferenceFunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/grammar': {
      id: '/zh/reference/grammar'
      path: '/zh/reference/grammar'
      fullPath: '/zh/reference/grammar'
      preLoaderRoute: typeof ZhReferenceGrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/interop': {
      id: '/zh/reference/interop'
      path: '/zh/reference/interop'
      fullPath: '/zh/reference/interop'
      preLoaderRoute: typeof ZhReferenceInteropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/lexical': {
      id: '/zh/reference/lexical'
      path: '/zh/reference/lexical'
      fullPath: '/zh/reference/lexical'
      preLoaderRoute: typeof ZhReferenceLexicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/modules': {
      id: '/zh/reference/modules'
      path: '/zh/reference/modules'
      fullPath: '/zh/reference/modules'
      preLoaderRoute: typeof ZhReferenceModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/ownership': {
      id: '/zh/reference/ownership'
      path: '/zh/reference/ownership'
      fullPath: '/zh/reference/ownership'
      preLoaderRoute: typeof ZhReferenceOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/pointers': {
      id: '/zh/reference/pointers'
      path: '/zh/reference/pointers'
      fullPath: '/zh/reference/pointers'
      preLoaderRoute: typeof ZhReferencePointersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/slices': {
      id: '/zh/reference/slices'
      path: '/zh/reference/slices'
      fullPath: '/zh/reference/slices'
      preLoaderRoute: typeof ZhReferenceSlicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/text': {
      id: '/zh/reference/text'
      path: '/zh/reference/text'
      fullPath: '/zh/reference/text'
      preLoaderRoute: typeof ZhReferenceTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/toolchain': {
      id: '/zh/reference/toolchain'
      path: '/zh/reference/toolchain'
      fullPath: '/zh/reference/toolchain'
      preLoaderRoute: typeof ZhReferenceToolchainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/types': {
      id: '/zh/reference/types'
      path: '/zh/reference/types'
      fullPath: '/zh/reference/types'
      preLoaderRoute: typeof ZhReferenceTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reference/utf': {
      id: '/zh/reference/utf'
      path: '/zh/reference/utf'
      fullPath: '/zh/reference/utf'
      preLoaderRoute: typeof ZhReferenceUtfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  PhilosophyRoute: PhilosophyRoute,
  UseCasesRoute: UseCasesRoute,
  FeaturesCompileTimeRoute: FeaturesCompileTimeRoute,
  FeaturesCppGenerationRoute: FeaturesCppGenerationRoute,
  FeaturesFailureContractsRoute: FeaturesFailureContractsRoute,
  LearnAggregatesRoute: LearnAggregatesRoute,
  LearnClosuresRoute: LearnClosuresRoute,
  LearnConstantsRoute: LearnConstantsRoute,
  LearnControlRoute: LearnControlRoute,
  LearnFailuresRoute: LearnFailuresRoute,
  LearnFormattingRoute: LearnFormattingRoute,
  LearnFunctionsRoute: LearnFunctionsRoute,
  LearnInteropRoute: LearnInteropRoute,
  LearnModulesRoute: LearnModulesRoute,
  LearnOwnershipRoute: LearnOwnershipRoute,
  LearnPointersRoute: LearnPointersRoute,
  LearnProjectRoute: LearnProjectRoute,
  LearnTestingRoute: LearnTestingRoute,
  LearnTextRoute: LearnTextRoute,
  LearnValuesRoute: LearnValuesRoute,
  LearnWorkflowRoute: LearnWorkflowRoute,
  ReferenceAggregatesRoute: ReferenceAggregatesRoute,
  ReferenceCliRoute: ReferenceCliRoute,
  ReferenceClosuresRoute: ReferenceClosuresRoute,
  ReferenceConstantsRoute: ReferenceConstantsRoute,
  ReferenceControlRoute: ReferenceControlRoute,
  ReferenceDiagnosticsRoute: ReferenceDiagnosticsRoute,
  ReferenceEntryTestingRoute: ReferenceEntryTestingRoute,
  ReferenceFailuresRoute: ReferenceFailuresRoute,
  ReferenceFormattingRoute: ReferenceFormattingRoute,
  ReferenceFunctionsRoute: ReferenceFunctionsRoute,
  ReferenceGrammarRoute: ReferenceGrammarRoute,
  ReferenceInteropRoute: ReferenceInteropRoute,
  ReferenceLexicalRoute: ReferenceLexicalRoute,
  ReferenceModulesRoute: ReferenceModulesRoute,
  ReferenceOwnershipRoute: ReferenceOwnershipRoute,
  ReferencePointersRoute: ReferencePointersRoute,
  ReferenceSlicesRoute: ReferenceSlicesRoute,
  ReferenceTextRoute: ReferenceTextRoute,
  ReferenceToolchainRoute: ReferenceToolchainRoute,
  ReferenceTypesRoute: ReferenceTypesRoute,
  ReferenceUtfRoute: ReferenceUtfRoute,
  Zh404Route: Zh404Route,
  ZhPhilosophyRoute: ZhPhilosophyRoute,
  ZhUseCasesRoute: ZhUseCasesRoute,
  LearnIndexRoute: LearnIndexRoute,
  ReferenceIndexRoute: ReferenceIndexRoute,
  ZhIndexRoute: ZhIndexRoute,
  ZhFeaturesCompileTimeRoute: ZhFeaturesCompileTimeRoute,
  ZhFeaturesCppGenerationRoute: ZhFeaturesCppGenerationRoute,
  ZhFeaturesFailureContractsRoute: ZhFeaturesFailureContractsRoute,
  ZhLearnAggregatesRoute: ZhLearnAggregatesRoute,
  ZhLearnClosuresRoute: ZhLearnClosuresRoute,
  ZhLearnConstantsRoute: ZhLearnConstantsRoute,
  ZhLearnControlRoute: ZhLearnControlRoute,
  ZhLearnFailuresRoute: ZhLearnFailuresRoute,
  ZhLearnFormattingRoute: ZhLearnFormattingRoute,
  ZhLearnFunctionsRoute: ZhLearnFunctionsRoute,
  ZhLearnInteropRoute: ZhLearnInteropRoute,
  ZhLearnModulesRoute: ZhLearnModulesRoute,
  ZhLearnOwnershipRoute: ZhLearnOwnershipRoute,
  ZhLearnPointersRoute: ZhLearnPointersRoute,
  ZhLearnProjectRoute: ZhLearnProjectRoute,
  ZhLearnTestingRoute: ZhLearnTestingRoute,
  ZhLearnTextRoute: ZhLearnTextRoute,
  ZhLearnValuesRoute: ZhLearnValuesRoute,
  ZhLearnWorkflowRoute: ZhLearnWorkflowRoute,
  ZhReferenceAggregatesRoute: ZhReferenceAggregatesRoute,
  ZhReferenceCliRoute: ZhReferenceCliRoute,
  ZhReferenceClosuresRoute: ZhReferenceClosuresRoute,
  ZhReferenceConstantsRoute: ZhReferenceConstantsRoute,
  ZhReferenceControlRoute: ZhReferenceControlRoute,
  ZhReferenceDiagnosticsRoute: ZhReferenceDiagnosticsRoute,
  ZhReferenceEntryTestingRoute: ZhReferenceEntryTestingRoute,
  ZhReferenceFailuresRoute: ZhReferenceFailuresRoute,
  ZhReferenceFormattingRoute: ZhReferenceFormattingRoute,
  ZhReferenceFunctionsRoute: ZhReferenceFunctionsRoute,
  ZhReferenceGrammarRoute: ZhReferenceGrammarRoute,
  ZhReferenceInteropRoute: ZhReferenceInteropRoute,
  ZhReferenceLexicalRoute: ZhReferenceLexicalRoute,
  ZhReferenceModulesRoute: ZhReferenceModulesRoute,
  ZhReferenceOwnershipRoute: ZhReferenceOwnershipRoute,
  ZhReferencePointersRoute: ZhReferencePointersRoute,
  ZhReferenceSlicesRoute: ZhReferenceSlicesRoute,
  ZhReferenceTextRoute: ZhReferenceTextRoute,
  ZhReferenceToolchainRoute: ZhReferenceToolchainRoute,
  ZhReferenceTypesRoute: ZhReferenceTypesRoute,
  ZhReferenceUtfRoute: ZhReferenceUtfRoute,
  ZhLearnIndexRoute: ZhLearnIndexRoute,
  ZhReferenceIndexRoute: ZhReferenceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
